Update build files
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>

diff --git a/.github/workflows/python-lib-release.yml b/.github/workflows/python-lib-release.yml
--- a/.github/workflows/python-lib-release.yml
+++ b/.github/workflows/python-lib-release.yml
@@ -1,4 +1,3 @@
-# Note: default release notes file is docs/release.md.
 name: Release and deploy to Pypi
 
 on:
@@ -8,8 +7,6 @@ jobs:
   release-checks:
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
-    outputs:
-      version: ${{ steps.check.outputs.release-version }}
     env:
       SLACK_NOTIFICATION: YES
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
@@ -18,17 +15,8 @@ jobs:
       - name: Release checks and update version for release
         id: check
         run: |
-          source /scripts/common.sh
           /scripts/release-checks.sh --python setup.py
-          FILE=docs/release.md
-          if [ -f "$FILE" ]; then
-            export release_date=$(date +'%d %B %Y')
-            /scripts/finalize-version.sh --python setup.py $FILE 'sed -i -e "s/TBD/$release_date/g"'
-          else
-            /scripts/finalize-version.sh --python setup.py
-          fi
-          version=$(grep version setup.py | cut -d= -f2 | tr -d '",')
-          echo "::set-output name=release-version::$(echo $version)"
+          /scripts/finalize-version.sh --python setup.py
         shell: bash
 
       - name: Cache licence-check
@@ -41,16 +29,19 @@ jobs:
         uses: zepben/licence-check-action@main
         with:
           LC_URL: ${{ secrets.LC_URL }}
+          PATH: src
 
   deploy:
     runs-on: ubuntu-latest
-    container: python:3.7-alpine
+    container: python:3.7
     needs: release-checks
-
+    outputs:
+      artifact: ${{ steps.build.outputs.artifact }}
+      version: ${{ steps.build.outputs.version }}
     steps:
       - name: Install dependencies
         run: |
-          apk add tar curl bash gcc musl-dev libffi-dev openssl-dev git
+          pip install tox twine
 
       - uses: actions/checkout@v2
 
@@ -61,30 +52,27 @@ jobs:
           git checkout release
         shell: bash
 
-      - name: Cache python deps
-        uses: actions/cache@v2
-        with:
-          path: /pipcache
-          key: pip
-
       - name: Build and publish
         id: build
         env:
           TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
           TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-          VERSION: ${{ needs.release-checks.outputs.version }}
         run: |
-          mkdir -p /pipcache
-          pip install --cache-dir /pipcache twine
-          pip install --cache-dir /pipcache -r requirements.txt
-          # pytest
-          python setup.py sdist bdist_wheel
+          tox
           twine upload dist/*
-          artifact="zepben.cimbend-${VERSION}-py3-none-any.whl"
+          version=$(grep version setup.py | cut -d= -f2 | tr -d '",')
+          artifact="zepben.auth-${version}-py3-none-any.whl"
+          echo "::set-output name=version::$(echo $version)"
           echo "::set-output name=artifact::$(echo $artifact)"
           echo "::set-output name=artifact-path::$(echo dist/$artifact)"
         shell: bash
         continue-on-error: true
+
+      - uses: actions/upload-artifact@master
+        if: steps.build.outcome == 'success'
+        with:
+          name: ${{ steps.build.outputs.artifact }}
+          path: ${{ steps.build.outputs.artifact-path }}
 
       - name: Delete release branch if deploy failed and fail
         if: steps.build.outcome == 'failure'
@@ -94,10 +82,16 @@ jobs:
           exit 1
         shell: bash
 
+  create-release:
+    needs: [deploy]
+    runs-on: ubuntu-latest
+    container: zepben/pipeline-basic:5.0.0
+    steps:
+      - uses: actions/checkout@v2
       - name: Merge and Tag
         id: merge
         env:
-          VERSION: ${{ needs.release-checks.outputs.version }}
+          VERSION: ${{ needs.deploy.outputs.version }}
         run: |
           git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
           git fetch --all
@@ -108,7 +102,16 @@ jobs:
           echo "::set-output name=tag::$(echo v$VERSION)"
         shell: bash
 
+      - name: Fail
+        if: steps.merge.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in merging the branch. release branch was deleted."
+          exit 1
+        shell: bash
+
       - name: Create Release
+        if: steps.merge.outcome == 'success'
         id: create_release
         uses: actions/create-release@v1
         env:
@@ -116,9 +119,15 @@ jobs:
         with:
           tag_name: ${{ steps.merge.outputs.tag }}
           release_name: ${{ steps.merge.outputs.tag }}
-          body_path: docs/release.md
+          body_path: changelog.md
           draft: false
           prerelease: false
+
+      - name: Download binary
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ needs.deploy.outputs.artifact }}
+          path: built-artifacts
 
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
@@ -126,16 +135,18 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ steps.build.outputs.artifact-path }}
-          asset_name: ${{ steps.build.outputs.artifact }}
+          asset_path: built-artifacts/${{ needs.deploy.outputs.artifact }}
+          asset_name: ${{ needs.deploy.outputs.artifact }}
           asset_content_type: application/octet-stream
-        continue-on-error: true
 
   update-version:
-    needs: deploy
+    needs: create-release
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
+      ZEPBEN_PYPI_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+      ZEPBEN_PYPI_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+      ZEPBEN_PYPI_REPO: ${{ secrets.ZEPBEN_PYPI_REPO }}
       SLACK_NOTIFICATION: YES
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     steps:
@@ -143,12 +154,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          source /scripts/common.sh
-          FILE=docs/release.md
-          if [ -f "$FILE" ]; then
-            export ln=$(cat $FILE | grep -n "### v[0-9]\+.[0-9]\+.[0-9]\+" | head -1 | cut -d':' -f1)
-            /scripts/update-version.sh --python --release setup.py $FILE 'next_release_version=${version//-SNAPSHOT/} && sed -i "${ln}i \#\#\# v${version//-SNAPSHOT/}\n\n\#\#\#\#\# Breaking Changes\n\* None.\n\n\#\#\#\#\# New Features\n\* None.\n\n\#\#\#\#\# Enhancements\n\* None.\n\n\#\#\#\#\# Fixes\n\* None.\n\n\#\#\#\#\# Notes\n\* None.\n\n\-\-\-\n" $changelog && sed -i "5i \|\[${next_release_version}\]\(\#v${next_release_version//\./}\)\| \`TBD\` \|"'
-          else
-            /scripts/update-version.sh --python --release setup.py
-          fi
+          /scripts/update-version.sh --python --release setup.py changelog.md
         shell: bash
